openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the Physical AI & Humanoid Robotics Book RAG chatbot system
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

paths:
  /api/rag/query:
    post:
      summary: Query the RAG system with a question
      description: Submit a question to the RAG system and receive an answer based on book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request - invalid query format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/rag/validate:
    post:
      summary: Validate a query against book content
      description: Check if a query can be answered from book content before processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/content/chapters:
    get:
      summary: Get list of book chapters
      description: Retrieve metadata about all book chapters
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: object
                properties:
                  chapters:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chapter'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/content/chapters/{chapterId}:
    get:
      summary: Get specific chapter content
      description: Retrieve content of a specific chapter
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Chapter not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The question to ask the RAG system
          example: "What is the difference between ROS 1 and ROS 2?"
        context:
          type: string
          description: Optional context to narrow the search
          example: "chapter-2-ros2"
        userId:
          type: string
          description: Optional user identifier for conversation history
          example: "user-12345"

    QueryResponse:
      type: object
      required:
        - answer
        - sources
        - queryId
      properties:
        answer:
          type: string
          description: The answer generated by the RAG system
          example: "ROS 2 is the next generation of the Robot Operating System..."
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
          description: List of sources used to generate the answer
        queryId:
          type: string
          description: Unique identifier for this query
          example: "query-67890"
        confidence:
          type: number
          description: Confidence score for the answer (0-1)
          example: 0.95

    ValidationResponse:
      type: object
      required:
        - isValid
        - canAnswer
        - confidence
      properties:
        isValid:
          type: boolean
          description: Whether the query is properly formatted
        canAnswer:
          type: boolean
          description: Whether the query can be answered from book content
        confidence:
          type: number
          description: Confidence level in ability to answer (0-1)
        suggestedSources:
          type: array
          items:
            type: string
          description: Suggested chapters that might contain the answer

    Source:
      type: object
      required:
        - chapterId
        - chapterTitle
        - contentUrl
        - relevanceScore
      properties:
        chapterId:
          type: string
          description: ID of the source chapter
          example: "chapter-2-ros2"
        chapterTitle:
          type: string
          description: Title of the source chapter
          example: "The Robotic Nervous System (ROS 2)"
        contentUrl:
          type: string
          description: URL to the specific content location
          example: "/docs/ros2#architecture"
        relevanceScore:
          type: number
          description: Relevance score of this source to the query (0-1)
          example: 0.87
        textExcerpt:
          type: string
          description: Excerpt from the source content
          example: "ROS 2 is the next generation of the Robot Operating System..."

    Chapter:
      type: object
      required:
        - id
        - title
        - content
        - wordCount
        - sources
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
          example: "chapter-2-ros2"
        title:
          type: string
          description: Title of the chapter
          example: "The Robotic Nervous System (ROS 2)"
        content:
          type: string
          description: Markdown content of the chapter
          example: "# The Robotic Nervous System\n\nROS 2 is the next generation..."
        wordCount:
          type: integer
          description: Number of words in the chapter
          example: 1850
        sources:
          type: array
          items:
            type: string
          description: List of APA-cited sources used in the chapter
          example: ["NVIDIA Isaac Documentation, 2024", "ROS 2 User Guide, 2024"]
        createdAt:
          type: string
          format: date-time
          description: When the chapter was created
          example: "2024-12-07T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: When the chapter was last updated
          example: "2024-12-07T15:30:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "QUERY_FAILED"
        message:
          type: string
          description: Human-readable error message
          example: "Failed to process query due to invalid format"
        details:
          type: object
          description: Additional error details
          example: {"field": "query", "reason": "required"}